name: test
run-name: ${{ github.actor }} is running unit tests
on: [push]
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    steps:
      # This allows the action to checkout repo
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install Pip dependencies
        run: python -m pip install --upgrade pip setuptools poetry
      - name: Install Poetry dependencies
        run: |
          rm poetry.lock
          poetry lock
          poetry install
      - name: Test with pytest
        run: poetry run pytest --cov=tests/ --cov-append
